### ISSUE TITLE
HTTP /status page - incorrect rtr-connections count

### ISSUE THREAD

**Issue by rblayzor** [NLnetLabs/routinator#752] opened 2022-06-30 12:09 UTC
Routinator 0.11.2

On HTTP status page (/status) rtr-connections: seems to be incorrect count. (off by 1?)

I have four RTR connects, verified and up, yet rtr-connections on status page only shows 3.

**Comment by partim** [comment] 2022-06-30 14:33
Thank you for the report!

Interesting. There’s nothing obviously wrong with the code, so I guess I have to dive a bit deeper …

**Comment by partim** [comment] 2022-11-02 14:11
I think I fixed the issue in #811 and thus in 0.12.0-rc1, but since I was never able to reproduce it, I am not entirely sure. I will close the issue now, but please do re-open it if the problem persists.

**Closed by partim** 2022-11-02 14:11 UTC
