### ISSUE TITLE
rpsl file to small

### ISSUE THREAD

**Issue by matsm** [NLnetLabs/routinator#237] opened 2019-11-06 19:40 UTC
We run routinator 0.6.1

We are using the rpsl file in our process and we are generating this file with the command: 
routinator  -c /usr/local/etc/routinator.conf vrps -n --format rpsl —output rpki.db	

This has worked fine.

Sometime yesterday we discovered that the resulting file was only 10% of it´s previously size.
After some struggling we found that adding —disable-rrdp gave a file with a more normal size

routinator --disable-rrdp -c /usr/local/etc/routinator.conf vrps -n --format rpsl —output rpki.d

Please advice

/mm

**Comment by partim** [comment] 2019-11-07 09:47
That sure sounds odd. If RRDP doesn’t work, Routinator should fall back to using rsync.

I see that you have `-n` in your command. Are you running an update separately? What command are you using for that?

Is there any unusual output or logging?

**Comment by matsm** [comment] 2019-11-07 10:32
Hi

> On 7 Nov 2019, at 10:47, Martin Hoffmann <notifications@github.com> wrote:
> 
> That sure sounds odd. If RRDP doesn’t work, Routinator should fall back to using rsync.
> 
> I see that you have -n in your command. Are you running an update separately?

Yes

> What command are you using for that?

/usr/local/bin/routinator -c /usr/local/etc/routinator.conf server --detach --http=127.0.0.1:789

> 
> Is there any unusual output or logging?


Yes :)

There is a strange thing that I discovered

If I run the command 

shell> /usr/local/bin/routinator  -c /usr/local/etc/routinator.conf vrps -n --format rpsl —output mats.db

as a normal user, there is lots of error in the logfile but the resulting rspl file is of the  right  size

shell> ls -lh 
-rw-r-----  1 mats  mats    22M Nov  7 10:55 mats.db

From the logfile:

Nov 07 10:46:44 hostname routinator[23817]: /var/spool/routinator/repository/rrdp/3835556993: bad RRDP server directory. Skipping.
Nov 07 10:46:44 hostname routinator[23817]: /var/spool/routinator/repository/rrdp/1508669157: bad RRDP server directory. Skipping.
Nov 07 10:46:44 hostname routinator[23817]: /var/spool/routinator/repository/rrdp/3046056725: bad RRDP server directory. Skipping.
Nov 07 10:46:44 hostname routinator[23817]: /var/spool/routinator/repository/rrdp/1635745779: bad RRDP server directory. Skipping.
Nov 07 10:46:44 hostname routinator[23817]: /var/spool/routinator/repository/rrdp/2043953270: bad RRDP server directory. Skipping.
Nov 07 10:46:44 hostname routinator[23817]: /var/spool/routinator/repository/rrdp/4177618787: bad RRDP server directory. Skipping.
Nov 07 10:46:44 hostname routinator[23817]: /var/spool/routinator/repository/rrdp/2455363039: bad RRDP server directory. Skipping.
Nov 07 10:46:44 hostname routinator[23817]: /var/spool/routinator/repository/rrdp/1743194671: bad RRDP server directory. Skipping.
Nov 07 10:46:44 hostname routinator[23817]: /var/spool/routinator/repository/rrdp/1843523026: bad RRDP server directory. Skipping.
Nov 07 10:46:44 hostname routinator[23817]: /var/spool/routinator/repository/rrdp/3370990142: bad RRDP server directory. Skipping.
Nov 07 10:46:44 hostname routinator[23817]: rsyncing from rsync://rpki.afrinic.net/repository/.
Nov 07 10:46:44 hostname routinator[23817]: rsyncing from rsync://rpki.ripe.net/ta/.
Nov 07 10:46:44 hostname routinator[23817]: rsync://rpki.afrinic.net/repository: Running command "rsync" "--contimeout=10" "--timeout=300" "-rltz" "--delete" "rsync://rpki.afrinic.net/repository/" "/var/spool/routinator/repository/rsync/rpki.afrinic.net/repository/"
Nov 07 10:46:44 hostname routinator[23817]: rsync://rpki.ripe.net/ta: Running command "rsync" "--contimeout=10" "--timeout=300" "-rltz" "--delete" "rsync://rpki.ripe.net/ta/" "/var/spool/routinator/repository/rsync/rpki.ripe.net/ta/"
Nov 07 10:46:44 hostname routinator[23817]: rsyncing from rsync://rpki.apnic.net/repository/.
Nov 07 10:46:44 hostname routinator[23817]: rsyncing from rsync://rpki.arin.net/repository/.
Nov 07 10:46:44 hostname routinator[23817]: rsyncing from rsync://repository.lacnic.net/rpki/.
Nov 07 10:46:44 hostname routinator[23817]: rsync://rpki.apnic.net/repository: Running command "rsync" "--contimeout=10" "--timeout=300" "-rltz" "--delete" "rsync://rpki.apnic.net/repository/" "/var/spool/routinator/repository/rsync/rpki.apnic.net/repository/"
Nov 07 10:46:44 hostname routinator[23817]: rsync://rpki.arin.net/repository: Running command "rsync" "--contimeout=10" "--timeout=300" "-rltz" "--delete" "rsync://rpki.arin.net/repository/" "/var/spool/routinator/repository/rsync/rpki.arin.net/repository/"
Nov 07 10:46:44 hostname routinator[23817]: rsync://repository.lacnic.net/rpki: Running command "rsync" "--contimeout=10" "--timeout=300" "-rltz" "--delete" "rsync://repository.lacnic.net/rpki/" "/var/spool/routinator/repository/rsync/repository.lacnic.net/rpki/"
Nov 07 10:46:44 hostname routinator[23817]: rsync://rpki.ripe.net/ta: successfully completed.
Nov 07 10:46:44 hostname routinator[23817]: rsync://rpki.ripe.net/ta: The RIPE NCC Certification Repository is subject to Terms and Conditions
Nov 07 10:46:44 hostname routinator[23817]: rsync://rpki.ripe.net/ta: See http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc
Nov 07 10:46:44 hostname routinator[23817]: rsync://rpki.ripe.net/ta: 
Nov 07 10:46:44 hostname routinator[23817]: Found valid trust anchor rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer. Processing.
Nov 07 10:46:44 hostname routinator[23817]: RRDP https://rrdp.ripe.net/notification.xml: Updating server
Nov 07 10:46:47 hostname routinator[23817]: rsync://rpki.afrinic.net/repository: successfully completed.
Nov 07 10:46:47 hostname routinator[23817]: Found valid trust anchor rsync://rpki.afrinic.net/repository/AfriNIC.cer. Processing.
Nov 07 10:46:47 hostname routinator[23817]: rsync://rpki.afrinic.net/repository/member_repository/F367890A/D5950BFE814611E98A26EC23F8AEA228/2DD43A5EA98511E99FCBF40FF8AEA228.roa: processing failed.
Nov 07 10:46:48 hostname routinator[23817]: rsync://rpki.apnic.net/repository: successfully completed.
Nov 07 10:46:48 hostname routinator[23817]: Found valid trust anchor rsync://rpki.apnic.net/repository/apnic-rpki-root-iana-origin.cer. Processing.
Nov 07 10:46:48 hostname routinator[23817]: RRDP https://rrdp.apnic.net/notification.xml: Updating server
Nov 07 10:46:49 hostname routinator[23817]: rsync://rpki.arin.net/repository: successfully completed.
Nov 07 10:46:49 hostname routinator[23817]: Found valid trust anchor rsync://rpki.arin.net/repository/arin-rpki-ta.cer. Processing.
Nov 07 10:46:50 hostname routinator[23817]: rsync://repository.lacnic.net/rpki: successfully completed.
Nov 07 10:46:50 hostname routinator[23817]: Found valid trust anchor rsync://repository.lacnic.net/rpki/lacnic/rta-lacnic-rpki.cer. Processing.
Nov 07 10:47:14 hostname routinator[23817]: https://rrdp.ripe.net/notification.xml: https://rrdp.ripe.net/notification.xml: timed out
Nov 07 10:47:14 hostname routinator[23817]: Marking RRPD server 'https://rrdp.ripe.net/notification.xml' as unusable
Nov 07 10:47:14 hostname routinator[23817]: rsyncing from rsync://rpki.ripe.net/repository/.
Nov 07 10:47:14 hostname routinator[23817]: rsync://rpki.ripe.net/repository: Running command "rsync" "--contimeout=10" "--timeout=300" "-rltz" "--delete" "rsync://rpki.ripe.net/repository/" "/var/spool/routinator/repository/rsync/rpki.ripe.net/repository/"
Nov 07 10:47:18 hostname routinator[23817]: https://rrdp.apnic.net/notification.xml: https://rrdp.apnic.net/notification.xml: timed out
Nov 07 10:47:18 hostname routinator[23817]: Marking RRPD server 'https://rrdp.apnic.net/notification.xml' as unusable
Nov 07 10:47:18 hostname routinator[23817]: rsyncing from rsync://rpki.apnic.net/member_repository/.
Nov 07 10:47:18 hostname routinator[23817]: rsync://rpki.apnic.net/member_repository: Running command "rsync" "--contimeout=10" "--timeout=300" "-rltz" "--delete" "rsync://rpki.apnic.net/member_repository/" "/var/spool/routinator/repository/rsync/rpki.apnic.net/member_repository/"
Nov 07 10:47:29 hostname routinator[23817]: rsync://rpki.apnic.net/member_repository: successfully completed.
Nov 07 10:47:29 hostname routinator[23817]: RRDP https://rrdp.twnic.tw/rrdp/notify.xml: Updating server
Nov 07 10:47:34 hostname routinator[23817]: rsync://rpki.ripe.net/repository: successfully completed.
Nov 07 10:47:34 hostname routinator[23817]: rsync://rpki.ripe.net/repository: The RIPE NCC Certification Repository is subject to Terms and Conditions


running the same command as root

shell#> usr/local/bin/routinator  -c /usr/local/etc/routinator.conf vrps -n --format rpsl —output root.db

shell#> ls -lh root.db 
-rw-r--r--  1 root  mats   3.0M Nov  7 11:04 root.db

Nov 07 11:04:47 hostname routinator[71906]: /var/spool/routinator/repository/rrdp/3835556993: bad RRDP server directory. Skipping.
Nov 07 11:04:47 hostname routinator[71906]: /var/spool/routinator/repository/rrdp/1508669157: bad RRDP server directory. Skipping.
Nov 07 11:04:47 hostname routinator[71906]: /var/spool/routinator/repository/rrdp/3046056725: bad RRDP server directory. Skipping.
Nov 07 11:04:47 hostname routinator[71906]: /var/spool/routinator/repository/rrdp/1635745779: bad RRDP server directory. Skipping.
Nov 07 11:04:47 hostname routinator[71906]: /var/spool/routinator/repository/rrdp/2043953270: bad RRDP server directory. Skipping.
Nov 07 11:04:47 hostname routinator[71906]: /var/spool/routinator/repository/rrdp/4177618787: bad RRDP server directory. Skipping.
Nov 07 11:04:47 hostname routinator[71906]: /var/spool/routinator/repository/rrdp/2455363039: bad RRDP server directory. Skipping.
Nov 07 11:04:47 hostname routinator[71906]: /var/spool/routinator/repository/rrdp/1743194671: bad RRDP server directory. Skipping.
Nov 07 11:04:47 hostname routinator[71906]: /var/spool/routinator/repository/rrdp/1843523026: bad RRDP server directory. Skipping.
Nov 07 11:04:47 hostname routinator[71906]: /var/spool/routinator/repository/rrdp/3370990142: bad RRDP server directory. Skipping.
Nov 07 11:04:47 hostname routinator[71906]: Found valid trust anchor rsync://rpki.afrinic.net/repository/AfriNIC.cer. Processing.
Nov 07 11:04:47 hostname routinator[71906]: Found valid trust anchor rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer. Processing.
Nov 07 11:04:47 hostname routinator[71906]: Found valid trust anchor rsync://rpki.apnic.net/repository/apnic-rpki-root-iana-origin.cer. Processing.
Nov 07 11:04:47 hostname routinator[71906]: Found valid trust anchor rsync://repository.lacnic.net/rpki/lacnic/rta-lacnic-rpki.cer. Processing.
Nov 07 11:04:47 hostname routinator[71906]: Found valid trust anchor rsync://rpki.arin.net/repository/arin-rpki-ta.cer. Processing.
Nov 07 11:04:47 hostname routinator[71906]: rsync://rpki.ripe.net/repository/ripe-ncc-ta.mft not found in its RRDP repository.
Nov 07 11:04:47 hostname routinator[71906]: rsync://rpki.ripe.net/repository/ripe-ncc-ta.mft: failed to load.
Nov 07 11:04:47 hostname routinator[71906]: rsync://rpki.apnic.net/repository/838DB214166511E2B3BC286172FD1FF2/C5zKkN0Neoo3ZmsZIX_g2EA3t6I.mft not found in its RRDP repository.
Nov 07 11:04:47 hostname routinator[71906]: rsync://rpki.apnic.net/repository/838DB214166511E2B3BC286172FD1FF2/C5zKkN0Neoo3ZmsZIX_g2EA3t6I.mft: failed to load.
Nov 07 11:04:47 hostname routinator[71906]: rsync://rpki.afrinic.net/repository/member_repository/F367890A/D5950BFE814611E98A26EC23F8AEA228/2DD43A5EA98511E99FCBF40FF8AEA228.roa::
Nov 07 10:47:34 hostname routinator[23817]: rsync://rpki.ripe.net/repository: See http://www.ripe.net/lir-services/ncc/legal/certification/repository-tc
Nov 07 10:47:34 hostname routinator[23817]: rsync://rpki.ripe.net/repository: 
Nov 07 10:47:38 hostname routinator[23817]: RRDP https://ca.rg.net/rrdp/notify.xml: Updating server
Nov 07 10:47:59 hostname routinator[23817]: https://rrdp.twnic.tw/rrdp/notify.xml: https://rrdp.twnic.tw/rrdp/notify.xml: timed out
Nov 07 10:47:59 hostname routinator[23817]: Marking RRPD server 'https://rrdp.twnic.tw/rrdp/notify.xml' as unusable
Nov 07 10:47:59 hostname routinator[23817]: rsyncing from rsync://rpkica.twnic.tw/rpki/.
Nov 07 10:47:59 hostname routinator[23817]: rsync://rpkica.twnic.tw/rpki: Running command "rsync" "--contimeout=10" "--timeout=300" "-rltz" "--delete" "rsync://rpkica.twnic.tw/rpki/" "/var/spool/routinator/repository/rsync/rpkica.twnic.tw/rpki/"
Nov 07 10:48:08 hostname routinator[23817]: https://ca.rg.net/rrdp/notify.xml: https://ca.rg.net/rrdp/notify.xml: timed out
Nov 07 10:48:08 hostname routinator[23817]: Marking RRPD server 'https://ca.rg.net/rrdp/notify.xml' as unusable
Nov 07 10:48:08 hostname routinator[23817]: rsyncing from rsync://ca.rg.net/rpki/.
Nov 07 10:48:08 hostname routinator[23817]: rsync://ca.rg.net/rpki: Running command "rsync" "--contimeout=10" "--timeout=300" "-rltz" "--delete" "rsync://ca.rg.net/rpki/" "/var/spool/routinator/repository/rsync/ca.rg.net/rpki/"
Nov 07 10:48:09 hostname routinator[23817]: rsync://rpkica.twnic.tw/rpki: successfully completed.
Nov 07 10:48:09 hostname routinator[23817]: rsyncing from rsync://rpki-repository.nic.ad.jp/ap/.
Nov 07 10:48:09 hostname routinator[23817]: rsync://rpki-repository.nic.ad.jp/ap: Running command "rsync" "--contimeout=10" "--timeout=300" "-rltz" "--delete" "rsync://rpki-repository.nic.ad.jp/ap/" "/var/spool/routinator/repository/rsync/rpki-repository.nic.ad.jp/ap/"
Nov 07 10:48:10 hostname routinator[23817]: rsync://ca.rg.net/rpki: successfully completed.
Nov 07 10:48:14 hostname routinator[23817]: rsync://rpki-repository.nic.ad.jp/ap: successfully completed.
Nov 07 10:48:14 hostname routinator[23817]: RRDP https://rpki.cnnic.cn/rrdp/notify.xml: Updating server
Nov 07 10:48:44 hostname routinator[23817]: https://rpki.cnnic.cn/rrdp/notify.xml: https://rpki.cnnic.cn/rrdp/notify.xml: timed out
Nov 07 10:48:44 hostname routinator[23817]: Marking RRPD server 'https://rpki.cnnic.cn/rrdp/notify.xml' as unusable
Nov 07 10:48:44 hostname routinator[23817]: rsyncing from rsync://rpki.cnnic.cn/rpki/.
Nov 07 10:48:44 hostname routinator[23817]: rsync://rpki.cnnic.cn/rpki: Running command "rsync" "--contimeout=10" "--timeout=300" "-rltz" "--delete" "rsync://rpki.cnnic.cn/rpki/" "/var/spool/routinator/repository/rsync/rpki.cnnic.cn/rpki/"
Nov 07 10:48:49 hostname routinator[23817]: rsync://rpki.cnnic.cn/rpki: successfully completed.
Nov 07 10:48:50 hostname routinator[23817]: Diff with 0 announced and 0 withdrawn.
Nov 07 10:48:50 hostname routinator[23817]: Validation completed. New serial is 32.
Nov 07 10:54:45 hostname routinator[71224]: /var/spool/routinator/repository/rrdp/3835556993: bad RRDP server directory. Skipping.
Nov 07 10:54:45 hostname routinator[71224]: /var/spool/routinator/repository/rrdp/1508669157: bad RRDP server directory. Skipping.
Nov 07 10:54:45 hostname routinator[71224]: /var/spool/routinator/repository/rrdp/3046056725: bad RRDP server directory. Skipping.
Nov 07 10:54:45 hostname routinator[71224]: /var/spool/routinator/repository/rrdp/1635745779: bad RRDP server directory. Skipping.
Nov 07 10:54:45 hostname routinator[71224]: /var/spool/routinator/repository/rrdp/2043953270: bad RRDP server directory. Skipping.
Nov 07 10:54:45 hostname routinator[71224]: /var/spool/routinator/repository/rrdp/4177618787: bad RRDP server directory. Skipping.
Nov 07 10:54:45 hostname routinator[71224]: /var/spool/routinator/repository/rrdp/2455363039: bad RRDP server directory. Skipping.
Nov 07 10:54:45 hostname routinator[71224]: /var/spool/routinator/repository/rrdp/1743194671: bad RRDP server directory. Skipping.
Nov 07 10:54:45 hostname routinator[71224]: /var/spool/routinator/repository/rrdp/1843523026: bad RRDP server directory. Skipping.
Nov 07 10:54:45 hostname routinator[71224]: /var/spool/routinator/repository/rrdp/3370990142: bad RRDP server directory. Skipping.
Nov 07 10:54:45 hostname routinator[71224]: Found valid trust anchor rsync://rpki.afrinic.net/repository/AfriNIC.cer. Processing.
Nov 07 10:54:45 hostname routinator[71224]: Found valid trust anchor rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer. Processing.
Nov 07 10:54:45 hostname routinator[71224]: Found valid trust anchor rsync://rpki.apnic.net/repository/apnic-rpki-root-iana-origin.cer. Processing.
Nov 07 10:54:45 hostname routinator[71224]: Found valid trust anchor rsync://repository.lacnic.net/rpki/lacnic/rta-lacnic-rpki.cer. Processing.
Nov 07 10:54:45 hostname routinator[71224]: Failed to create unique directory under /var/spool/routinator/repository/rrdp: Permission denied (os error 13)
Nov 07 10:54:45 hostname routinator[71224]: Found valid trust anchor rsync://rpki.arin.net/repository/arin-rpki-ta.cer. Processing.
Nov 07 10:54:45 hostname routinator[71224]: Failed to create unique directory under /var/spool/routinator/repository/rrdp: Permission denied (os error 13)
Nov 07 10:54:45 hostname routinator[71224]: rsync://rpki.afrinic.net/repository/member_repository/F367890A/D5950BFE814611E98A26EC23F8AEA228/2DD43A5EA98511E99FCBF40FF8AEA228.roa: processing failed.
Nov 07 10:54:46 hostname routinator[71224]: Failed to create unique directory under /var/spool/routinator/repository/rrdp: Permission denied (os error 13)
Nov 07 10:57:00 hostname routinator[23817]: scheduling Read for: 0
Nov 07 10:57:00 hostname routinator[23817]: adding I/O source: 33554433
Nov 07 10:57:00 hostname routinator[23817]: scheduling Read for: 1
Nov 07 10:57:00 hostname routinator[23817]: read 87 bytes
Nov 07 10:57:00 hostname routinator[23817]: parsed 3 headers
Nov 07 10:57:00 hostname routinator[23817]: incoming body is empty
Nov 07 10:57:00 hostname routinator[23817]: flushed 3974 bytes
Nov 07 10:57:00 hostname routinator[23817]: scheduling Read for: 1
Nov 07 10:57:00 hostname routinator[23817]: read 0 bytes
Nov 07 10:57:00 hostname routinator[23817]: read eof
Nov 07 10:57:00 hostname routinator[23817]: dropping I/O source: 1


I can add that I´m running this on FreeBSD 11.2 and Debian 10, I get the same result from them both.

I have initialised the repository several times ( routinator init) but the problem is still there.


When I run the command as root or normal user

/usr/local/bin/routinator --disable-rrdp -c /usr/local/etc/routinator.conf vrps -n --format rpsl --output root.db

The resulting file size is ok and the logfile shows:

Nov 07 11:26:26 hostname routinator[72784]: Found valid trust anchor rsync://rpki.afrinic.net/repository/AfriNIC.cer. Processing.
Nov 07 11:26:26 hostname routinator[72784]: Found valid trust anchor rsync://rpki.ripe.net/ta/ripe-ncc-ta.cer. Processing.
Nov 07 11:26:26 hostname routinator[72784]: Found valid trust anchor rsync://rpki.apnic.net/repository/apnic-rpki-root-iana-origin.cer. Processing.
Nov 07 11:26:26 hostname routinator[72784]: Found valid trust anchor rsync://repository.lacnic.net/rpki/lacnic/rta-lacnic-rpki.cer. Processing.
Nov 07 11:26:26 hostname routinator[72784]: Found valid trust anchor rsync://rpki.arin.net/repository/arin-rpki-ta.cer. Processing.
Nov 07 11:26:26 hostname routinator[72784]: rsync://rpki.afrinic.net/repository/member_repository/F367890A/D5950BFE814611E98A26EC23F8AEA228/2DD43A5EA98511E99FCBF40FF8AEA228.roa: processing failed.



/mm

**Comment by partim** [comment] 2019-11-07 11:01
It looks like this is ultimately caused by not being able to talk to the RRDP server:

```
https://rrdp.ripe.net/notification.xml: https://rrdp.ripe.net/notification.xml: timed out
```

This happens for all the RRDP servers. It might be firewall issues or IPv6 connectivity problems.

It looks like what makes this all go really haywire is some issues in the RRDP code when `-n` is used. I will investigate this.

Ultimately, I would suggest not to mix server mode with vrps mode as that may lead to one updating the data while the other is reading from it. Dealing with that on the filesystem is tricky.

You can also get your RPSL from the HTTP server – or you could if there weren’t a bug which makes the `/rpsl` endpoint produce CSV output. This will be fixed in the next release. I would then suggest to get the data via

```
curl http://127.0.0.1:789/rpsl
```

**Comment by matsm** [comment] 2019-11-07 11:08
> On 7 Nov 2019, at 12:01, Martin Hoffmann <notifications@github.com> wrote:
> 
> It looks like this is ultimately caused by not being able to talk to the RRDP server:
> 
> https://rrdp.ripe.net/notification.xml: https://rrdp.ripe.net/notification.xml: timed out
> 
> This happens for all the RRDP servers. It might be firewall issues or IPv6 connectivity problems.
> 
> It looks like what makes this all go really haywire is some issues in the RRDP code when -n is used. I will investigate this.
> 
> Ultimately, I would suggest not to mix server mode with vrps mode as that may lead to one updating the data while the other is reading from it. Dealing with that on the filesystem is tricky.

What precisely do you suggest?

To turn off the 

/usr/local/bin/routinator -c /usr/local/etc/routinator.conf server --detach —http=127.0.0.1:789

and instead use 

/usr/local/bin/routinator --disable-rrdp -c /usr/local/etc/routinator.conf vrps --format rpsl --output rpki.db

(without the -n option)

/mm

**Comment by partim** [comment] 2019-11-07 11:14
Yes. I would also suggest to investigate why the HTTPS connections time out and fix that. Then you can leave out the `--disable-rrdp` option.

**Comment by matsm** [comment] 2019-11-07 12:12
I can't do much about connectivity problems i “the other end”.

I am running this on three machines in different networks and all of them showed the same problem about the same time.

The problem occurred yesterday and before that I run this for month without problem.

But I will follow your advice and turn off the server mode and don´t use the -n flag when generating the rpsl file

Thanks

/mm

**Comment by partim** [comment] 2020-04-17 10:16
I think the issue with `-n` was fixed. So I can close the issue. If you feel like there should be something done still, please do not hesitate to reopen!

**Closed by partim** 2020-04-17 10:16 UTC
