### ISSUE TITLE
Delete repository directories that disappeared

### ISSUE THREAD

**Issue by partim** [NLnetLabs/routinator#50] opened 2018-12-20 14:25 UTC
Currently, we only ever add new rsync modules to the repository tree. If such a module is not used anymore (i.e., it is never reference in any of the objects encountered) it should be removed.

**Comment by morrowc** [comment] 2019-07-10 18:59
Issue #168  is a dupe of this, please move this along :)

**Closed** 2019-07-17 12:15 UTC
