### ISSUE TITLE
RTR validation session stuck at Ex-Full (JunOS) after update to 0.6.3

### ISSUE THREAD

**Issue by edugas** [NLnetLabs/routinator#254] opened 2019-11-28 17:05 UTC
Hello,

I've upgraded one of the two Routinator RPKI validators and the one at 0.6.3 (with updated Rust installation). Upon reboot, I see Routinator listening on 3323 (RTR), 8080 (web) but when I check the routers, the validation sessions are stuck in Ex-Full.

We're running:

- latest Ubuntu 18.04 LTS
- rustup 1.20.2
- Routinator 0.6.3 (installed via cargo 1.39.0)

**Comment by edugas** [comment] 2019-11-28 17:49
So I did a full shutdown of the VM and boot it again and now the validation sessions are "Full"...

**Comment by edugas** [comment] 2019-11-28 19:19
Still ongoing...

Nov 28 13:13:56 rpki CRON[1052]: (rpki) CMD (/home/rpki/.cargo/bin/routinator server -d --rtr 172.93.x.x:3323 --http 172.93.x.x:8080)
Nov 28 13:14:21 rpki routinator[1117]: Sending fatal alert BadCertificate
Nov 28 13:24:42 rpki routinator[1117]: Sending fatal alert BadCertificate
Nov 28 13:35:19 rpki routinator[1117]: Sending fatal alert BadCertificate

**Comment by partim** [comment] 2019-11-28 20:09
Those messages are fine. They come from rg.net’s RRDP service which uses a self-signed certificate which Routinator doesn’t like. I am filtering those log messages for stderr and file logging, but there was no easy way to get that done for syslog and I haven’t yet had time to look into it more closely. I’ll schedule that for soon.

**Comment by edugas** [comment] 2019-11-28 21:05
Yeah, I've followed a false path in my troubleshooting.

Note that I was able to restore the RTR sessions with my routers by upgrading to 0.6.4-pre. Also, the HTTP server doesn't respond anymore (might just open another issue since it's probably not related).

When I do a curl on port 8080/status, I get absolutely nothing...

**Comment by partim** [comment] 2019-11-28 22:21
It seems it gets stuck right on start with a 20% or so probability. This seems to be in the new signal handling code.

At this point 0.6.4-pre are identical 0.6.3, so I guess it working for you was just luck. I am not quite sure yet whether it is fine when it started okay or if it also gets stuck while running. But I guess restarting until it works is workaround until there’s a fix – which obviously will be very soon.

**Comment by partim** [comment] 2019-11-29 00:38
I have committed and merged a fix to master (aka 0.6.4-pre) that seems to work fine. If it does indeed turn out to solve the issue, I will release 0.6.4 tomorrow.

**Comment by hellerve** [comment] 2019-11-29 09:22
Since this happens in code introduced by me, I’ll go ahead and apologize for introducing the regression!

**Comment by partim** [comment] 2019-11-29 10:14
Hi @hellerve, I should have caught the issue during code review and tests, so releasing Routinator with the issue is entirely my fault. Please don’t let this discourage you from contributing to open source projects. We really do appreciate you volunteering to help!

**Comment by hellerve** [comment] 2019-11-29 11:13
Oh, no, I’m extremely relaxed about this. Errors happen to the best of us :)

**Closed** 2020-03-04 13:55 UTC
